# This is a basic workflow to help you get started with Actions

name: deploy-ml-bundle

# Controls when the workflow will run
on:

  workflow_dispatch:
    inputs:
      project-name:
        type: string
        required: true
        default: false
      feature-store:
        type: boolean
        required: true
        default: false
      inference:
        type: choice
        description: Type of inference required whle serving the model
        options:
          - batch
          - streaming
        required: true
        default: batch
      environment:
        type: choice
        description: Environment where the bundle will be deployed
        options:
          - dev
          - test
          - acc
          - prd
        required: true
        default: batch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ################################################# Job called "test"
  migration:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prd
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out source code
        uses: actions/checkout@v3

      - name: install dependencies
        run: |
          echo "Hi I am Oscar!"
