# This is a basic workflow to help you get started with Actions

name: deploy-ml-bundle

# Controls when the workflow will run
on:

  workflow_dispatch:
    inputs:
      project-name:
        type: string
        required: true
      feature-store:
        type: boolean
        required: true
        default: false
      inference:
        type: choice
        description: Type of inference required whle serving the model
        options:
          - batch
          - streaming
        required: true
        default: batch
      environment:
        type: choice
        description: Environment where the bundle will be deployed
        options:
          - dev
          - test
          - acc
          - prd
        required: true
        default: batch

env:
  PYTHON_VERSION: '3.10'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ################################################# Job called "test"
  deploy-bundle:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prd
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install dependencies
        run: |
          echo "Hi I am Oscar!"
          sudo apt update
          sudo apt install curl unzip -y
          python -m pip install --upgrade pip
          https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh
          databricks --version
          databricks bundle init --help
          # databricks bundle init --config-file xxx
          # read this https://docs.databricks.com/en/dev-tools/bundles/settings.html#bundle-syntax-mappings